name: @RFOF_BOT

# Token und Chat-ID aus Umgebungsvariablen lesen
TOKEN = os.getenv("6774549752:AAFx5D-reu3Pu-qkmKLh2aNxumv4faZtRN0")
CHAT_ID = "6386147374"  # Hier die spezifische Chat-ID einfügen


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Stelle sicher, dass die Python-Version zu deinem Projekt passt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Stelle sicher, dass alle erforderlichen Pakete in requirements.txt aufgeführt sind

      - name: Run Telegram Bot
        run: |
          python path/to/your_script.py  # Ersetze 'path/to/your_script.py' durch den tatsächlichen Pfad zu deinem Python-Skript
