name: [ main ]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-curl

      - name: Compile Telegram Bot
        run: |
          gcc -o telegram_bot telegram_bot.c -lcurl  

      - name: Run Telegram Bot
        run: |
          ./telegram_bot
