name: RFOF Nano Perpetuum CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    strategy:
      matrix:
        server: [ubuntu-latest, liteserver-1, liteserver-2, BOx-to-BOx, Nano-Perpetuum-Mobile, other-server-1, other-server-2, other-server-3, other-server-4, other-server-5]

    runs-on: ${{ matrix.server }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        npm install
        pip install -r requirements.txt

    - name: Initialize blockchain languages
      run: |
        python setup_42.py
        python setup_420.py

    - name: Run hello_rfof_network.py
      run: python hello_rfof_network.py
