name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2

    - name[_{{{CITATION{{{_1{](https://github.com/MicrosoftDocs/azure-docs.de-de/tree/50ddafcbd8ea557c6b29d5cc0f6ba12c5e607c6c/articles%2Fazure-functions%2Ffunctions-how-to-github-actions.md)[_{{{CITATION{{{_2{](https://github.com/brianyaucy/AzurePentestBeginner/tree/18bcfd110d484546eee658a05621d37e6b8c0078/l01-labreport.md)
