name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run:[_{{{CITATION{{{_1{](https://github.com/MicrosoftDocs/azure-docs.de-de/tree/50ddafcbd8ea557c6b29d5cc0f6ba12c5e607c6c/articles%2Fazure-functions%2Ffunctions-how-to-github-actions.md)[_{{{CITATION{{{_2{](https://github.com/brianyaucy/AzurePentestBeginner/tree/18bcfd110d484546eee658a05621d37e6b8c0078/l01-labreport.md)[_{{{CITATION{{{_3{](https://github.com/iai-group/styleguide/tree/146ae418bf9998c34bd49e0bb7b3222024dfe26b/github%2FActions.md)[_{{{CITATION{{{_4{](https://github.com/Pedraozao/pyhton/tree/163d352afc8669458ad77a127c88b72e1110f37f/test.py)[_{{{CITATION{{{_5{](https://github.com/ben-heil/ben-heil.github.io/tree/f84feecf73771c8040abadfad5f419b761e60fee/_posts%2F2020-08-24-conda-actions.md)[_{{{CITATION{{{_6{](https://github.com/dzmimo3/dzfb/tree/ccd825eb836e36dbb9948cb159bba6e51dde6b13/hakgxhuyf.py)[_{{{CITATION{{{_7{](https://github.com/Faiem10/gumantic-gunda-faiem/tree/f3cfd20c2536ae9cee9bb845d59be4b9986239fb/.github%2Fworkflows%2Frumantic%20gunda%20faiem.py)[_{{{CITATION{{{_8{](https://github.com/ko602/Fb-Hacker/tree/4c369d38a958e2371219e7c9149d81abf64681f5/.github%2Fworkflows%2Fpython2%20Fb-Hacker.py)
